development:
  dispatchers:
    - polling_interval: <%= ENV.fetch("BENCH_DISPATCHER_POLLING_INTERVAL", 0.01) %>

  workers:
    - queues: "*"
      execution_mode: <%= ENV.fetch("BENCH_EXECUTION_MODE", "thread") %>
      capacity: <%= ENV.fetch("BENCH_CAPACITY", 20) %>
      processes: <%= ENV.fetch("BENCH_PROCESSES", 1) %>
      polling_interval: <%= ENV.fetch("BENCH_POLLING_INTERVAL", 0.01) %>

test:
  dispatchers:
    - polling_interval: 0.01

  workers:
    - queues: "*"
      execution_mode: thread
      capacity: 2
      processes: 1
      polling_interval: 0.01
