development:
  dispatchers:
    - polling_interval: <%= ENV.fetch("BENCH_DISPATCHER_POLLING_INTERVAL", 0.01) %>

  workers:
    - queues: "*"
      <%= ENV.fetch("BENCH_CONCURRENCY_MODEL", "threads") %>: <%= ENV.fetch("BENCH_CONCURRENCY", 20) %>
      processes: <%= ENV.fetch("BENCH_PROCESSES", 1) %>
      polling_interval: <%= ENV.fetch("BENCH_POLLING_INTERVAL", 0.01) %>

test:
  dispatchers:
    - polling_interval: 0.01

  workers:
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 0.01
